#!/usr/bin/env bash
echo "running set up for redis $1"

die () {
        echo "ERROR: $1. Aborting!"
        exit 1
}


SCRIPT=$(readlink -f $0)                    #Absolute path to this script
SCRIPTPATH=$(dirname $SCRIPT)               #Absolute path this script is in


VERSION="stable"
URL = "http://download.redis.io/redis-stable.tar.gz"

sudo yum install -y make gcc tcl nano

# update hosts
#cat /vagrant/redis-hosts.txt | sudo tee -a /etc/hosts

# install redis

URL=$([ "$VERSION" == "stable" ] && echo  "http://download.redis.io/redis-stable.tar.gz" || echo"http://download.redis.io/releases/redis-$VERSION.tar.gz")
 wget  $URL
 tar xfz redis-$VERSION.tar.gz
rm redis-$VERSION.tar.gz
  cd redis-$VERSION
make
sudo make install 

DEFAULT_CONFIG="${SCRIPTPATH}/../redis.conf"
REDIS_PORT=$([$2]&& echo $2 ||echo "6379")
REDIS_CONFIG_FILE="/etc/redis/$REDIS_PORT.conf"
REDIS_LOG_FILE="/var/log/redis_$REDIS_PORT.log"
REDIS_DATA_DIR="/var/lib/redis/$REDIS_PORT"
REDIS_EXECUTABLE=`command -v redis-server`
CLI_EXEC=`dirname $REDIS_EXECUTABLE`"/redis-cli"
TMP_FILE="/tmp/${REDIS_PORT}.conf"
INIT_TPL_FILE="${SCRIPTPATH}/redis_init_script.tpl"
INIT_SCRIPT_DEST="/etc/init.d/redis_${REDIS_PORT}"
PIDFILE="/var/run/redis_${REDIS_PORT}.pid"

echo "Selected config:"

echo "REDIS_PORT        :$REDIS_PORT"
echo "REDIS_CONFIG_FILE :$REDIS_CONFIG_FILE"
echo "REDIS_LOG_FILE    :$REDIS_LOG_FILE"
echo "REDIS_DATA_DIR    :$REDIS_DATA_DIR"
echo "CLI_EXEC          :$CLI_EXEC"
echo "TMP_FILE          :$TMP_FILE"
echo "INIT_TPL_FILE     :$INIT_TPL_FILE"
echo "INIT_SCRIPT_DEST  :$INIT_SCRIPT_DEST"
echo "PIDFILE           :$PIDFILE"

mkdir -p `dirname "$REDIS_CONFIG_FILE"` || die "Could not create redis config directory"
mkdir -p `dirname "$REDIS_LOG_FILE"` || die "Could not create redis log dir"
mkdir -p "$REDIS_DATA_DIR" || die "Could not create redis data directory"




echo "## Generated by install_server.sh ##" > $TMP_FILE


#make test 
#sudo bash -c "cat >> /etc/php5/apache2/php.ini" <<EOF